Make g++ as entrypoint & add test step in CI.

diff --git a/.github/workflows/docker-hub-publish.yml b/.github/workflows/docker-hub-publish.yml
--- a/.github/workflows/docker-hub-publish.yml
+++ b/.github/workflows/docker-hub-publish.yml
@@ -8,8 +8,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
-    - name: Build image
+    - name: Build
       run:  docker build . --tag rdok/gpp:alpine3.12
+    - name: Test
+      run:  |
+        ouput=$(docker run --rm -i rdok/gpp:alpine3.12 --version)
+        if [[ $output != *"g++ (Alpine"* ]]; then
+          echo "Expected g++ identifier was not found."
+          exit 1
+        fi
     - name: Docker login
       run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
     - name: Push image
